VAGRANTFILE_API_VERSION = "2"

k3s_token = nil
if File.file?(".env")
  line = File.readlines(".env", chomp: true).find { |l| l =~ /^\s*K3S_TOKEN=/ }
  k3s_token = line&.split("=", 2)&.last&.strip
end
abort("K3S_TOKEN manquant dans .env") if k3s_token.nil? || k3s_token.empty?

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	os_box      = "ubuntu/jammy64"
	provider    = "virtualbox"
	network     = "private_network"
	memory      = 1024
	cpus        = 1
	script_dir  = File.expand_path("scripts")
	controller = { name: "cedmulleS", hostname: "cedmulleS", ip: "192.168.56.110" }
	worker = { name: "cedmulleSW", hostname: "cedmulleSW", ip: "192.168.56.111" }

	config.vm.box = os_box

	# Server
	config.vm.define controller[:name] do |vm|
		vm.vm.hostname = controller[:hostname]
		vm.vm.network network, ip: controller[:ip]
		vm.vm.provider provider do |vb|
			vb.memory = memory
			vb.cpus  = cpus
		end
		vm.vm.provision "shell", path: "#{script_dir}/setup_k3s-controller.sh", args: [controller[:ip], k3s_token]
	end

	# Worker
	config.vm.define worker[:name] do |vm|
		vm.vm.hostname = worker[:hostname]
		vm.vm.network network, ip: worker[:ip]
		vm.vm.provider provider do |vb|
			vb.memory = memory
			vb.cpus  = cpus
		end
		vm.vm.provision "shell", path: "#{script_dir}/setup_k3s-worker.sh", args: [controller[:ip], worker[:ip], k3s_token]
	end
end
