Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "cduffautS" do |server|
    server.vm.hostname = "cduffautS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "cduffautS"
      vb.memory = "1024"
      vb.cpus = 1
    end

    server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  config.vm.define "cduffautSW" do |worker|
    worker.vm.hostname = "cduffautSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "cduffautSW"
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker.vm.provision "shell", inline: <<-SHELL
      apt-get update
      sleep 30
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -
    SHELL
  end
end
