apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        command: ["/bin/sh"]
        args: ["-c", "echo '<h1>Hello from App1!</h1><p>This is application 1</p>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
