apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        command: ["/bin/sh"]
        args: ["-c", "echo '<h1>Hello from App2!</h1><p>This is application 2 - Replica</p>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
