Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.define "cduffautS" do |server|
    server.vm.hostname = "cduffautS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 80, host: 8080
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "cduffautS-p2"
      vb.memory = "2048"
      vb.cpus = 2
    end

    server.vm.provision "shell", inline: <<-SHELL
      apt-get update
      curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --node-ip "192.168.56.110" --advertise-address "192.168.56.110"
      
      mkdir -p /home/vagrant/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config
      
      # wait k3s's ready
      sleep 30
      
      mkdir -p /home/vagrant/k8s-apps
      cp /vagrant/confs/*.yaml /home/vagrant/k8s-apps/ 2>/dev/null || true
      chown -R vagrant:vagrant /home/vagrant/k8s-apps
      sudo -u vagrant kubectl apply -f /home/vagrant/k8s-apps/ 2>/dev/null || true
    SHELL
  end
end